name:                GDirections
version:             0.1.0.0
github:              "onliner10/GDirections"
license:             BSD3
author:              "Mateusz Urban"
maintainer:          "mateuszurban2@gmail.com"
copyright:           "2023 Mateusz Urban"

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            Simple client to interact with Google Directions API
category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/onliner10/GDirections#README.md>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

default-extensions:
  - DeriveGeneric
  - OverloadedStrings

library:
  source-dirs: src
  dependencies:
    - bytestring
    - text
    - download-curl
    - containers
    - aeson
    - url
    - aeson-casing

